import { AlertOctagon, ArrowUpRight, CircleDollarSign, ShieldCheck, WalletCards } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Link } from 'react-router-dom'
import PageHeader from '../components/PageHeader'
import StatCard from '../components/StatCard'
import TransactionTable from '../components/TransactionTable'
import { useApp } from '../context/AppContext'

const chartData = [{ day: '16 jul', total: 32, suspicious: 3 }, { day: '17 jul', total: 48, suspicious: 6 }, { day: '18 jul', total: 41, suspicious: 4 }, { day: '19 jul', total: 62, suspicious: 8 }, { day: '20 jul', total: 54, suspicious: 7 }, { day: '21 jul', total: 73, suspicious: 11 }, { day: '22 jul', total: 58, suspicious: 9 }]
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', notation: 'compact', maximumFractionDigits: 1 })

export default function Dashboard() {
  const { transactions, loading } = useApp()
  const suspicious = transactions.filter((item) => item.status === 'suspicious')
  const totalValue = transactions.reduce((sum, item) => sum + item.amount, 0)
  return <><PageHeader eyebrow="Quarta-feira, 22 de julho de 2026" title="Visão geral" description="Monitore o fluxo de transações e concentre sua atenção onde o risco está crescendo." action={{ to: '/transactions/new', label: 'Registrar transação' }} />
    {loading ? <div className="loading-panel"><div className="spinner" />Carregando inteligência de risco...</div> : <>
      <div className="stats-grid"><StatCard label="Transações analisadas" value={transactions.length || 1284} detail="últimos 30 dias" trend="12,4%" icon={ArrowUpRight} tone="red" /><StatCard label="Volume movimentado" value={money.format(totalValue || 8420000)} detail="últimos 30 dias" trend="8,2%" icon={CircleDollarSign} tone="orange" /><StatCard label="Sinais de risco" value={suspicious.length || 47} detail="precisam de revisão" trend="-4,8%" icon={AlertOctagon} tone="dark" /><StatCard label="Taxa de aprovação" value="96,3%" detail="transações aprovadas" icon={ShieldCheck} tone="green" /></div>
      <div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-heading"><div><span className="section-kicker">Atividade</span><h2>Fluxo de transações</h2></div><div className="legend"><span><i className="legend-dot total" />Total</span><span><i className="legend-dot risk" />Suspeitas</span></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ top: 10, right: 8, left: -20, bottom: 0 }}><defs><linearGradient id="totalFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#e24639" stopOpacity=".22" /><stop offset="100%" stopColor="#e24639" stopOpacity="0" /></linearGradient><linearGradient id="riskFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ee9b36" stopOpacity=".24" /><stop offset="100%" stopColor="#ee9b36" stopOpacity="0" /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e7e9ed" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#9096a1' }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#9096a1' }} /><Tooltip contentStyle={{ border: '1px solid #e6e8ec', borderRadius: 8, boxShadow: '0 8px 24px #1b24300f' }} /><Area type="monotone" dataKey="total" stroke="#d53d32" strokeWidth={2.5} fill="url(#totalFill)" /><Area type="monotone" dataKey="suspicious" stroke="#ec9a31" strokeWidth={2} fill="url(#riskFill)" /></AreaChart></ResponsiveContainer></div></section>
        <section className="panel risk-panel"><div className="panel-heading"><div><span className="section-kicker">Agora</span><h2>Radar de risco</h2></div><Link to="/rules" className="text-link">Configurar <ArrowUpRight size={14} /></Link></div><div className="risk-score"><div className="score-ring"><strong>{Math.min(99, 82 + suspicious.length)}</strong><span>/ 100</span></div><div><strong>Risco controlado</strong><p>Os sinais de hoje estão abaixo da média semanal.</p></div></div><div className="risk-bars"><div><span>Valor alto <b>42%</b></span><i><em style={{ width: '42%' }} /></i></div><div><span>Horário incomum <b>28%</b></span><i><em style={{ width: '28%' }} /></i></div><div><span>Conta recém-criada <b>19%</b></span><i><em style={{ width: '19%' }} /></i></div></div></section></div>
      <section className="panel recent-panel"><div className="panel-heading"><div><span className="section-kicker">Revisão prioritária</span><h2>Transações recentes</h2></div><Link to="/transactions" className="text-link">Ver todas <ArrowUpRight size={14} /></Link></div><TransactionTable transactions={transactions.slice(0, 5)} compact /></section>
      <div className="quick-actions"><Link to="/transactions/new"><WalletCards size={18} /><span><strong>Registrar transação</strong><small>Envie uma operação para análise</small></span><ArrowUpRight size={16} /></Link><Link to="/rules"><ShieldCheck size={18} /><span><strong>Revisar regras</strong><small>Ajuste os critérios de risco</small></span><ArrowUpRight size={16} /></Link></div>
    </>}
  </>
}
