import { ArrowLeft, CalendarDays, CircleDollarSign, Info, Landmark, Send, UserRound } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useApp } from '../context/AppContext'

const initial = { account_id: '', destination_account_id: '', amount: '', currency: 'BRL', occurred_at: new Date().toISOString().slice(0, 16), destination_account_created_at: '' }

export default function NewTransaction() {
  const [form, setForm] = useState(initial); const [errors, setErrors] = useState({}); const [saving, setSaving] = useState(false); const { addTransaction } = useApp(); const navigate = useNavigate()
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }))
  const submit = async (event) => { event.preventDefault(); const nextErrors = {}; if (!form.account_id) nextErrors.account_id = 'Informe a conta de origem.'; if (!form.destination_account_id) nextErrors.destination_account_id = 'Informe a conta de destino.'; if (!form.amount || Number(form.amount) <= 0) nextErrors.amount = 'Informe um valor maior que zero.'; if (!form.occurred_at) nextErrors.occurred_at = 'Informe a data da operação.'; setErrors(nextErrors); if (Object.keys(nextErrors).length) return; setSaving(true); await addTransaction({ ...form, amount: Number(form.amount), destination_account_created_at: form.destination_account_created_at || null, occurred_at: new Date(form.occurred_at).toISOString() }); setSaving(false); navigate('/transactions') }
  return <><Link to="/transactions" className="back-link"><ArrowLeft size={16} /> Voltar para transações</Link><div className="page-header form-header"><div><div className="eyebrow">Entrada manual</div><h1>Registrar transação</h1><p>O motor de risco analisará a operação assim que ela for enviada.</p></div><div className="secure-note"><Landmark size={17} /> Dados protegidos</div></div><form className="form-layout" onSubmit={submit}><section className="panel form-panel"><div className="form-section-title"><span className="step-number">01</span><div><h2>Dados da operação</h2><p>Identifique as contas e o valor movimentado.</p></div></div><div className="field-grid"><Field label="Conta de origem" icon={UserRound} value={form.account_id} onChange={(value) => update('account_id', value)} placeholder="Ex.: ACC-100" error={errors.account_id} /><Field label="Conta de destino" icon={Send} value={form.destination_account_id} onChange={(value) => update('destination_account_id', value)} placeholder="Ex.: ACC-200" error={errors.destination_account_id} /><Field label="Valor da transação" icon={CircleDollarSign} type="number" value={form.amount} onChange={(value) => update('amount', value)} placeholder="0,00" error={errors.amount} /><div className="field"><label>Moeda</label><div className="input-icon"><CircleDollarSign size={16} /><select value={form.currency} onChange={(event) => update('currency', event.target.value)}><option>BRL</option><option>USD</option><option>EUR</option></select></div></div></div></section><section className="panel form-panel"><div className="form-section-title"><span className="step-number">02</span><div><h2>Contexto temporal</h2><p>Esses dados ajudam a detectar anomalias de horário e contas novas.</p></div></div><div className="field-grid"><Field label="Data e hora da operação" icon={CalendarDays} type="datetime-local" value={form.occurred_at} onChange={(value) => update('occurred_at', value)} error={errors.occurred_at} /><Field label="Criação da conta de destino" icon={CalendarDays} type="datetime-local" value={form.destination_account_created_at} onChange={(value) => update('destination_account_created_at', value)} hint="Opcional · usado na regra de conta recém-criada" /></div><div className="info-banner"><Info size={17} /><span>A análise é automática. Uma transação pode acionar mais de uma regra e ficará marcada como suspeita para revisão.</span></div></section><div className="form-actions"><Link to="/transactions" className="button secondary">Cancelar</Link><button className="button primary" disabled={saving}>{saving ? <span className="button-spinner" /> : <Send size={16} />}{saving ? 'Analisando...' : 'Enviar para análise'}</button></div></form></>
}

function Field({ label, icon: Icon, value, onChange, type = 'text', placeholder, error, hint }) { return <div className="field"><label>{label}</label><div className={error ? 'input-icon invalid' : 'input-icon'}><Icon size={16} /><input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></div>{error ? <small className="field-error">{error}</small> : hint && <small className="field-hint">{hint}</small>}</div> }
