import { ArrowLeft, CalendarClock, ChevronRight, Clock3, Copy, Hash, MapPin, ShieldAlert, UserRound } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import StatusBadge from '../components/StatusBadge'
import { useApp } from '../context/AppContext'

const labels = { high_amount: 'Valor acima do limite', repeated_transaction: 'Transação repetida em curto intervalo', new_destination_account: 'Conta de destino recém-criada', unusual_hour: 'Padrão incomum de horário' }
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
const fullDate = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long', timeStyle: 'short' })

export default function TransactionDetails() {
  const { id } = useParams(); const { transactions } = useApp(); const item = transactions.find((transaction) => String(transaction.id) === id)
  if (!item) return <div className="not-found"><ShieldAlert size={32} /><h1>Transação não encontrada</h1><Link to="/transactions" className="button secondary">Voltar para transações</Link></div>
  return <><Link to="/transactions" className="back-link"><ArrowLeft size={16} /> Voltar para transações</Link><div className="detail-header"><div><div className="eyebrow">Investigação #{item.id}</div><h1>Detalhes da transação</h1><p>{fullDate.format(new Date(item.occurred_at))}</p></div><StatusBadge status={item.status} /></div><div className="detail-grid"><section className="panel detail-main"><div className="amount-hero"><span>Valor movimentado</span><strong>{money.format(item.amount)}</strong><small>{item.currency} · operação analisada automaticamente</small></div><div className="detail-fields"><div><span><UserRound size={14} />Conta de origem</span><strong>{item.account_id}</strong></div><div><span><MapPin size={14} />Conta de destino</span><strong>{item.destination_account_id}</strong></div><div><span><CalendarClock size={14} />Data da operação</span><strong>{fullDate.format(new Date(item.occurred_at))}</strong></div><div><span><Clock3 size={14} />Registrada em</span><strong>{fullDate.format(new Date(item.created_at))}</strong></div></div><div className="account-history"><div className="subheading"><h2>Histórico da conta</h2><span>Últimos 30 dias</span></div><div className="history-row"><div className="history-icon green">✓</div><div><strong>Conta ativa e verificada</strong><small>Sem alterações cadastrais recentes</small></div><span>há 12 dias</span></div><div className="history-row"><div className="history-icon orange">↗</div><div><strong>3 transferências para {item.destination_account_id}</strong><small>Comportamento observado pelo motor</small></div><span>este mês</span></div></div></section><aside className="panel analysis-card"><div className="panel-heading"><div><span className="section-kicker">Motor de análise</span><h2>Sinais detectados</h2></div><div className="analysis-score">{item.triggered_rules.length}<small>sinais</small></div></div>{item.triggered_rules.length ? <div className="detected-rules">{item.triggered_rules.map((rule) => <div className="detected-rule" key={rule}><div className="rule-alert"><ShieldAlert size={16} /></div><div><strong>{labels[rule] || rule}</strong><p>{rule === 'high_amount' ? 'O valor supera o limite configurado para esta conta.' : rule === 'unusual_hour' ? 'A operação ocorreu entre 00:00 e 05:00.' : 'O padrão diverge do comportamento esperado.'}</p></div></div>)}</div> : <div className="clean-result"><div><ShieldAlert size={22} /></div><strong>Nenhum sinal acionado</strong><p>Esta operação passou pelas regras atuais sem inconsistências.</p></div>}<div className="analysis-meta"><span><Hash size={14} /> ID da análise</span><strong>ANL-{item.id}-2026 <Copy size={13} /></strong></div></aside></div></>
}
